const themes = [
  { id: 0, emoji: "🍎", name: "Apple", color: "#ff0800" },
  { id: 1, emoji: "🍏", name: "Green Apple", color: "#7cb342" },
  { id: 2, emoji: "🍊", name: "Tangerine", color: "#ff9800" },
  { id: 3, emoji: "🍋", name: "Lemon", color: "#ffeb3b" },
  { id: 4, emoji: "🍌", name: "Banana", color: "#ffeb3b" },
  { id: 5, emoji: "🍉", name: "Watermelon", color: "#f44336" },
  { id: 6, emoji: "🍇", name: "Grapes", color: "#673ab7" },
  { id: 7, emoji: "🍓", name: "Strawberry", color: "#e91e63" },
  { id: 8, emoji: "🍈", name: "Melon", color: "#8bc34a" },
  { id: 9, emoji: "🍒", name: "Cherry", color: "#d32f2f" },
  { id: 10, emoji: "🍑", name: "Peach", color: "#ff5722" },
  { id: 11, emoji: "🍍", name: "Pineapple", color: "#ffeb3b" },
  { id: 12, emoji: "🥭", name: "Mango", color: "#ff9800" },
  { id: 13, emoji: "🥥", name: "Coconut", color: "#795548" },
  { id: 14, emoji: "🥝", name: "Kiwi", color: "limegreen" },
  { id: 15, emoji: "🍅", name: "Tomato", color: "#ff6347" },
  { id: 16, emoji: "🍆", name: "Eggplant", color: "#9c27b0" },
  { id: 17, emoji: "🥑", name: "Avocado", color: "#4caf50" },
  { id: 18, emoji: "🥦", name: "Broccoli", color: "#4caf50" },
  { id: 19, emoji: "🥒", name: "Cucumber", color: "#8bc34a" },
  { id: 20, emoji: "🌶️", name: "Hot Pepper", color: "#f44336" },
  { id: 21, emoji: "🌽", name: "Corn", color: "#ffeb3b" },
  { id: 22, emoji: "🥕", name: "Carrot", color: "#ff9800" },
  { id: 23, emoji: "🥔", name: "Potato", color: "#9e9e9e" },
  { id: 24, emoji: "🍠", name: "Sweet Potato", color: "#ff5722" },
  { id: 25, emoji: "🥐", name: "Croissant", color: "#795548" },
  { id: 26, emoji: "🥖", name: "Baguette", color: "#795548" },
  { id: 27, emoji: "🥨", name: "Pretzel", color: "#795548" },
  { id: 28, emoji: "🥯", name: "Bagel", color: "#795548" },
  { id: 29, emoji: "🥞", name: "Pancakes", color: "#795548" },
];
export default themes;
